apiVersion: v1
kind: Service
metadata:
  name: ttms-deploy-service
  labels:
    app: ttms
spec:
  type: NodePort
  selector: 
    app: ttms
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31231
